### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by spike01** [makersacademy/makers-blog-theme#22]
From Ruben: Add something like discus to each blog posts?

**Comment by leoallen85** [comment]
I generally find comments on blog post a crappy thing, I'd argue against this unless we think there's a strong reason to want to get user feedback - maybe better to just give them a contact address?

**Comment by rubenkostucki** [comment]
I was reading this blog post and realised that we can't even let people leave comments :( 

http://blog.makersacademy.com/stop-worrying-about-what-youre-doing-with-your-life/

**Comment by sjmog** [comment]
I think the big problem with comments is that they then require moderation and management

**Comment by sjmog** [comment]
Plus old comments make a blog post look old and irrelevant

IMO they are more trouble than they are worth @rubenkostucki

**Comment by leoallen85** [comment]
:+1:
